#!/usr/bin/env bash

set -euo pipefail

# -----------------------------------------------------------------------------
# Vibe Coding Platform interactive activation script.
# Collects essential configuration values, writes the `.env` files and
# optionally launches the stack with `docker compose`.
# -----------------------------------------------------------------------------

ROOT_DIR="${VIBE_ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
CONFIG_DIR="$ROOT_DIR/config"
ENV_FILE="$ROOT_DIR/.env"
CONFIG_ENV_FILE="$CONFIG_DIR/.env"
EXAMPLE_FILE="$CONFIG_DIR/.env.example"
BUILD_IMAGES_SCRIPT="$ROOT_DIR/tools/build-project-images.sh"

if [[ ! -f "$EXAMPLE_FILE" ]]; then
  echo "[setup] Missing template: $EXAMPLE_FILE" >&2
  exit 1
fi

mkdir -p "$CONFIG_DIR"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

read_with_default() {
  local prompt="$1"
  local default="$2"
  local var
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " var || true
  else
    read -r -p "$prompt: " var || true
  fi
  if [[ -z "${var:-}" ]]; then
    echo "$default"
  else
    echo "$var"
  fi
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
  fi
}

echo "[setup] Vibe Coding Platform activation"
echo "[setup] Press enter to accept the default in brackets."
echo

DATA_DIR=$(read_with_default "Data directory for projects/logs" "${DATA_DIR:-/srv/vibe}")
echo "[setup] Ensuring data directories exist under '$DATA_DIR'..."
mkdir -p "$DATA_DIR"/projects "$DATA_DIR"/logs "$DATA_DIR"/tmp "$DATA_DIR"/redis || {
  echo "[setup] Failed to create data directories inside $DATA_DIR" >&2
  exit 1
}
API_PORT=$(read_with_default "API port" "${API_PORT:-9000}")
DOMAIN=$(read_with_default "Primary domain" "${DOMAIN:-localhost}")
API_KEY_DEFAULT=${API_KEY:-$(generate_secret)}
API_KEY=$(read_with_default "API key for clients" "$API_KEY_DEFAULT")
MASTER_DEFAULT=${MASTER_API_KEY:-$API_KEY}
MASTER_API_KEY=$(read_with_default "Master admin API key" "$MASTER_DEFAULT")
DB_PASS_DEFAULT=${DB_PASSWORD:-$(generate_secret)}
DB_PASSWORD=$(read_with_default "Database encryption password" "$DB_PASS_DEFAULT")
ALERT_EMAIL=$(read_with_default "Alert email recipient" "${ADMIN_ALERT_EMAIL:-alerts@example.com}")

GITHUB_SECRETS_KEY_VALUE=${GITHUB_SECRETS_KEY:-$(generate_secret)}
GITHUB_SECRETS_PATH_VALUE="${GITHUB_SECRETS_PATH:-/data/github-secrets.bin}"

echo "[setup] Generated GitHub secrets encryption key."

API_HOST=$(read_with_default "API host binding" "${API_HOST:-0.0.0.0}")

cat >"$ENV_FILE" <<EOF
# Generated by tools/setup/activate.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
API_HOST=$API_HOST
API_PORT=$API_PORT
DOMAIN=$DOMAIN
API_KEY=$API_KEY
MASTER_API_KEY=$MASTER_API_KEY
ADMIN_ALERT_EMAIL=$ALERT_EMAIL

DATA_DIR=$DATA_DIR
PROJECTS_DIR=/projects
LOGS_DIR=/logs

DB_TYPE=sqlite
DB_PATH=/data/projects.db
DB_PASSWORD=$DB_PASSWORD

GITHUB_SECRETS_PATH=$GITHUB_SECRETS_PATH_VALUE
GITHUB_SECRETS_KEY=$GITHUB_SECRETS_KEY_VALUE

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0

MAX_PROJECTS_PER_USER=10
PROJECT_CPU_LIMIT=2.0
PROJECT_MEMORY_LIMIT=4G
PROJECT_STORAGE_LIMIT=10G

EXEC_TIMEOUT=300
MAX_OUTPUT_SIZE=10485760

ENABLE_RATE_LIMIT=true
RATE_LIMIT_PER_MINUTE=100
RATE_LIMIT_WINDOW_SECONDS=60
EXEC_RATE_LIMIT_PER_MINUTE=60
PROJECT_CREATE_RATE_LIMIT=5
PROJECT_INFO_RATE_LIMIT=30
PASSWORD_ROTATE_RATE_LIMIT=4
PROJECT_DELETE_RATE_LIMIT=4

PROJECT_MANAGER_HOST=project-manager
PROJECT_MANAGER_PORT=9400
PROJECT_MANAGER_SCHEME=http
HEALTH_POLL_INTERVAL=30
CLEANUP_INTERVAL=86400
EOF

cp "$ENV_FILE" "$CONFIG_ENV_FILE"

echo "[setup] Wrote $ENV_FILE and $CONFIG_ENV_FILE"

PYTHON_BIN="${PYTHON_BIN:-python3}"
PIP_CMD=()
if command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  PIP_CMD=("$PYTHON_BIN" -m pip)
elif command -v python >/dev/null 2>&1; then
  PIP_CMD=(python -m pip)
elif command -v pip >/dev/null 2>&1; then
  PIP_CMD=(pip)
fi

if [[ ${#PIP_CMD[@]} -gt 0 ]]; then
  echo "[setup] Installing Python development dependencies..."
  if ! "${PIP_CMD[@]}" install -r "$ROOT_DIR/requirements-dev.txt"; then
    echo "[setup] Failed to install Python dependencies. Run 'pip install -r requirements-dev.txt' manually." >&2
  fi
else
  echo "[setup] Python or pip not found; skipping Python dependency installation." >&2
fi

if command -v docker >/dev/null 2>&1; then
  ensure_network() {
    local network_name="vibe-network"
    if docker network ls --format '{{.Name}}' | grep -qx "$network_name"; then
      echo "[setup] Docker network '$network_name' already exists."
    else
      echo "[setup] Creating docker network '$network_name'..."
      docker network create \
        --driver bridge \
        --subnet 172.30.0.0/16 \
        --opt com.docker.network.bridge.name=vibe0 \
        "$network_name"
    fi
  }

  build_project_images() {
    if [[ -x "$BUILD_IMAGES_SCRIPT" ]]; then
      echo "[setup] Building base project images..."
      "$BUILD_IMAGES_SCRIPT" || echo "[setup] Failed to build project images" >&2
    else
      echo "[setup] Project image builder not found ($BUILD_IMAGES_SCRIPT)." >&2
    fi
  }

  read -r -p "[setup] Start services with 'docker compose up -d'? [y/N]: " start_choice || true
  case "${start_choice,,}" in
    y|yes)
      echo "[setup] Launching docker compose stack..."
      ensure_network
      build_project_images
      docker compose up -d api project-manager cleanup redis
      docker compose ps
      ;;
    *)
      echo "[setup] Skipping docker compose start."
      ;;
  esac
else
  echo "[setup] Docker is not available in PATH; skipping service start." >&2
fi

echo "[setup] Activation completed."
