#!/usr/bin/env bash

set -euo pipefail

# -----------------------------------------------------------------------------
# Vibe Coding Platform - turn-key server bootstrapper
# -----------------------------------------------------------------------------
# This script is intended for administrators who already cloned the repository
# to the target machine and want a single entry-point to prepare the operating
# system, generate configuration files, and launch the Docker stack.
# -----------------------------------------------------------------------------

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMMON_LIB="$ROOT_DIR/install-common.sh"

if [[ ! -f "$COMMON_LIB" ]]; then
  echo "[setup] Unable to locate install-common.sh (expected at $COMMON_LIB)" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$COMMON_LIB"

DRY_RUN=false
AUTO_START=true
BUILD_IMAGES_STEP=true
FORCE_ENV=false
SKIP_PACKAGES=false
SKIP_DOCKER=false

DATA_DIR="${DATA_DIR:-/srv/vibe}"
DOMAIN="${DOMAIN:-localhost}"
API_PORT="${API_PORT:-9000}"
API_HOST="${API_HOST:-0.0.0.0}"
API_PUBLISH_MODE="${API_PUBLISH_MODE:-internal}"
if [[ ${API_PUBLISH_BIND+x} ]]; then
  API_PUBLISH_BIND="${API_PUBLISH_BIND}"
  API_PUBLISH_BIND_OVERRIDE=true
else
  API_PUBLISH_BIND=""
  API_PUBLISH_BIND_OVERRIDE=false
fi

usage() {
  cat <<'EOF'
Usage: tools/setup/server-setup.sh [options]

Options:
  --data-dir PATH         Location for persistent data (default: /srv/vibe)
  --domain DOMAIN         Primary domain used for generated routes (default: localhost)
  --api-port PORT         API port exposed by docker compose (default: 9000)
  --api-host HOST         API listen address inside the container (default: 0.0.0.0)
  --api-publish-mode MODE Exposure mode for docker publishing (internal|host, default: internal)
  --api-publish-bind IP   Bind address for docker publishing (overrides mode default)
  --no-start              Prepare everything but do not run docker compose up
  --no-build-images       Skip docker compose build and project image build step
  --force-env             Regenerate config/.env even if it already exists
  --skip-packages         Skip installing prerequisite OS packages
  --skip-docker           Skip Docker installation checks (assume docker is ready)
  --dry-run               Only validate OS compatibility, no changes performed
  -h, --help              Show this message

Environment variables:
  DATA_DIR, DOMAIN, API_PORT, API_HOST, API_PUBLISH_MODE, API_PUBLISH_BIND can override
  their respective defaults.
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --data-dir)
        DATA_DIR="$2"
        shift 2
        ;;
      --domain)
        DOMAIN="$2"
        shift 2
        ;;
      --api-port)
        API_PORT="$2"
        shift 2
        ;;
      --api-host)
        API_HOST="$2"
        shift 2
        ;;
      --api-publish-mode)
        API_PUBLISH_MODE="$2"
        shift 2
        ;;
      --api-publish-bind)
        API_PUBLISH_BIND="$2"
        API_PUBLISH_BIND_OVERRIDE=true
        shift 2
        ;;
      --no-start)
        AUTO_START=false
        shift
        ;;
      --no-build-images)
        BUILD_IMAGES_STEP=false
        shift
        ;;
      --force-env)
        FORCE_ENV=true
        shift
        ;;
      --skip-packages)
        SKIP_PACKAGES=true
        shift
        ;;
      --skip-docker)
        SKIP_DOCKER=true
        shift
        ;;
      --dry-run)
        DRY_RUN=true
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        warn "غير معروف: $1"
        usage
        exit 1
        ;;
    esac
  done
}

prepare_configuration() {
  mkdir -p "$ROOT_DIR/config"

  if [[ -f "$ROOT_DIR/config/.env" && $FORCE_ENV = false ]]; then
    warn "config/.env موجود مسبقاً – تخطي التوليد (استخدم --force-env لإعادة الإنشاء)"
    return 0
  fi

  log "توليد ملفات البيئة والتكوين..."

  local api_key master_key db_password github_key github_path project_manager_port
  local alert_email
  api_key=$(openssl rand -hex 32)
  master_key=$(openssl rand -hex 32)
  db_password=$(openssl rand -hex 24)
  github_key=$(openssl rand -hex 32)
  github_path="/data/github-secrets.bin"
  project_manager_port=9400
  alert_email="${ADMIN_ALERT_EMAIL:-alerts@example.com}"

  cat >"$ROOT_DIR/config/.env" <<EOF_ENV
# Vibe Coding Platform configuration
# Generated by tools/setup/server-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

API_HOST=$API_HOST
API_PORT=$API_PORT
DOMAIN=$DOMAIN
API_PUBLISH_MODE=$API_PUBLISH_MODE
API_PUBLISH_BIND=$API_PUBLISH_BIND
API_KEY=$api_key
MASTER_API_KEY=$master_key
ADMIN_ALERT_EMAIL=$alert_email

DATA_DIR=$DATA_DIR
PROJECTS_DIR=/projects
LOGS_DIR=/logs
INSTALL_DIR=$ROOT_DIR

DB_TYPE=sqlite
DB_PATH=/data/projects.db
DB_PASSWORD=$db_password

GITHUB_SECRETS_PATH=$github_path
GITHUB_SECRETS_KEY=$github_key

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0

MAX_PROJECTS_PER_USER=10
PROJECT_CPU_LIMIT=2.0
PROJECT_MEMORY_LIMIT=4G
PROJECT_STORAGE_LIMIT=10G

EXEC_TIMEOUT=300
MAX_OUTPUT_SIZE=10485760

ENABLE_RATE_LIMIT=true
RATE_LIMIT_PER_MINUTE=100
RATE_LIMIT_WINDOW_SECONDS=60
EXEC_RATE_LIMIT_PER_MINUTE=60
PROJECT_CREATE_RATE_LIMIT=5
PROJECT_INFO_RATE_LIMIT=30
PASSWORD_ROTATE_RATE_LIMIT=4
PROJECT_DELETE_RATE_LIMIT=4

PROJECT_MANAGER_PORT=$project_manager_port
PROJECT_MANAGER_HOST=project-manager
PROJECT_MANAGER_SCHEME=http
HEALTH_POLL_INTERVAL=30
CLEANUP_INTERVAL=86400
EOF_ENV

  cp "$ROOT_DIR/config/.env" "$ROOT_DIR/.env"
  chmod 600 "$ROOT_DIR/config/.env" "$ROOT_DIR/.env"

  if [[ -f "$ROOT_DIR/config/code-server/config.yaml" ]]; then
    local target_config="$DATA_DIR/code-server/config/config.yaml"
    mkdir -p "$(dirname "$target_config")"
    mkdir -p "$DATA_DIR/code-server" "$DATA_DIR/edge/credentials"

    if [[ ! -f "$target_config" || $FORCE_ENV = true ]]; then
      local code_password escaped_password
      code_password=$(openssl rand -hex 16)
      escaped_password=$(printf '%s' "$code_password" | sed 's/[&/\\]/\&/g')
      sed "s/__CODE_SERVER_PASSWORD__/$escaped_password/" \
        "$ROOT_DIR/config/code-server/config.yaml" >"$target_config"
      chmod 600 "$target_config"

      local htpasswd_template="$ROOT_DIR/config/code-server/traefik-users.htpasswd"
      local htpasswd_target="$DATA_DIR/edge/credentials/code-server-users.htpasswd"
      mkdir -p "$(dirname "$htpasswd_target")"
      if [[ -f "$htpasswd_template" ]]; then
        local htpasswd_hash escaped_hash
        htpasswd_hash=$(openssl passwd -apr1 "$code_password")
        escaped_hash=$(printf '%s' "$htpasswd_hash" | sed 's/[&/\\]/\&/g')
        sed "s/__CODE_SERVER_BASICAUTH__/$escaped_hash/" \
          "$htpasswd_template" >"$htpasswd_target"
        chmod 640 "$htpasswd_target"
      fi

      cat >"$DATA_DIR/code-server/credentials.txt" <<EOF_CREDS
username: coder
password: $code_password
EOF_CREDS
      chmod 600 "$DATA_DIR/code-server/credentials.txt"
    else
      warn "إعداد code-server موجود مسبقاً – تخطي الكتابة"
    fi
  fi

  success "تم إنشاء ملفات التكوين"
}

main() {
  parse_args "$@"

  case "$API_PUBLISH_MODE" in
    internal|host)
      ;;
    *)
      error "وضع النشر للـ API غير معروف: $API_PUBLISH_MODE (القيم المدعومة: internal, host)"
      ;;
  esac

  if [[ $API_PUBLISH_BIND_OVERRIDE = false || -z "$API_PUBLISH_BIND" ]]; then
    if [[ $API_PUBLISH_MODE = host ]]; then
      API_PUBLISH_BIND="0.0.0.0"
    else
      API_PUBLISH_BIND="127.0.0.1"
    fi
  fi

  INSTALL_DIR="$ROOT_DIR"
  export INSTALL_DIR
  export DATA_DIR
  export DOMAIN
  export API_PORT
  export API_PUBLISH_MODE
  export API_PUBLISH_BIND

  init_installation_context
  init_logging

  log "تهيئة نشر API: الوضع=$API_PUBLISH_MODE، bind=$API_PUBLISH_BIND"

  log "تهيئة منصة Vibe Coding داخل $INSTALL_DIR"

  check_root
  detect_distro
  require_supported_family "debian" "rhel" "suse"

  if [[ $DRY_RUN = true ]]; then
    success "وضع التجربة: التوزيعة مدعومة ويمكن متابعة التثبيت"
    exit 0
  fi

  if [[ $SKIP_PACKAGES = false ]]; then
    ensure_prerequisites
  else
    warn "تخطي تثبيت المتطلبات الأساسية كما طُلِب"
  fi

  if [[ $SKIP_DOCKER = false ]]; then
    ensure_docker
  else
    warn "تخطي فحص Docker كما طُلِب"
  fi

  create_directories
  prepare_configuration
  create_docker_network

  if [[ $BUILD_IMAGES_STEP = true ]]; then
    build_images
  else
    warn "تخطي بناء الصور (قد تحتاج لتشغيل tools/build-project-images.sh لاحقاً)"
  fi

  if [[ $AUTO_START = true ]]; then
    start_services
  else
    warn "تم تجهيز النظام بدون تشغيل الخدمات. استخدم 'docker compose up -d' عند الجاهزية"
  fi

  create_management_scripts
  show_summary
}

main "$@"
