"""End-to-end smoke test covering the main project workflow."""

from __future__ import annotations

import os
import uuid
from pathlib import Path
from typing import Dict

import pytest

pytestmark = pytest.mark.e2e


def _should_run() -> bool:
    """Return True when e2e tests are explicitly enabled."""

    flag = os.environ.get("RUN_E2E_TESTS", "").strip().lower()
    return flag in {"1", "true", "yes", "on"}


def _load_env() -> Dict[str, str]:
    """Load environment variables generated by the activation script."""

    root = Path(__file__).resolve().parents[2]
    candidates = []
    custom_path = os.environ.get("VIBE_E2E_ENV")
    if custom_path:
        candidates.append(Path(custom_path))
    candidates.append(root / ".env")
    candidates.append(root / "config" / ".env")

    for path in candidates:
        if not path.is_file():
            continue
        data: Dict[str, str] = {}
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            data[key.strip()] = value.strip().strip('"').strip("'")
        if data:
            return data
    return {}


@pytest.mark.skipif(not _should_run(), reason="RUN_E2E_TESTS is not enabled")
def test_project_lifecycle_via_httpx() -> None:
    """Exercise the API happy path using the public HTTP interface."""

    httpx = pytest.importorskip("httpx")

    env_data = _load_env()
    if "API_KEY" not in env_data:
        pytest.skip("Missing API_KEY in generated .env file")

    api_key = env_data["API_KEY"]
    master_key = env_data.get("MASTER_API_KEY") or api_key

    host = os.environ.get("VIBE_E2E_HOST") or env_data.get("DOMAIN") or "127.0.0.1"
    if host in {"0.0.0.0", ""}:
        host = "127.0.0.1"
    port = os.environ.get("VIBE_E2E_PORT") or env_data.get("API_PORT") or "9000"
    base_url = os.environ.get("VIBE_E2E_BASE_URL") or f"http://{host}:{port}"

    timeout = float(os.environ.get("VIBE_E2E_TIMEOUT", "60"))

    username = os.environ.get("VIBE_E2E_USERNAME", "gpt-e2e-user")
    project_suffix = uuid.uuid4().hex[:8]
    project_name = f"e2e-{project_suffix}"
    project_type = os.environ.get("VIBE_E2E_PROJECT_TYPE", "python")
    github_token = os.environ.get("VIBE_E2E_GITHUB_TOKEN", "ghp_" + "x" * 36)

    with httpx.Client(base_url=base_url, timeout=timeout) as client:
        # ------------------------------------------------------------------
        # Health check to ensure the stack is reachable.
        # ------------------------------------------------------------------
        health_response = client.get("/health")
        assert health_response.status_code == 200, health_response.text

        # ------------------------------------------------------------------
        # Step 1: Create a new project using the master API key.
        # ------------------------------------------------------------------
        create_payload = {
            "username": username,
            "project_name": project_name,
            "project_type": project_type,
            "github_api_key": github_token,
            "additional_secrets": {},
            "database": "sqlite",
            "redis": False,
        }
        create_headers = {"X-API-Key": master_key}
        create_response = client.post("/projects/create", json=create_payload, headers=create_headers)
        assert create_response.status_code == 200, create_response.text
        project_data = create_response.json()

        project_id = project_data["project_id"]
        project_password = project_data["password"]
        assert project_id
        assert project_password

        # Ensure metadata persisted (Redis/SQLite) by listing the projects for the user.
        list_headers = {"X-API-Key": master_key}
        list_response = client.get(f"/projects/{username}", headers=list_headers)
        assert list_response.status_code == 200, list_response.text
        listed_projects = list_response.json().get("projects", [])
        assert any(item["project_id"] == project_id for item in listed_projects)

        # ------------------------------------------------------------------
        # Step 2: Execute a simple command inside the project container.
        # ------------------------------------------------------------------
        exec_command = "printf 'hello-from-e2e' > e2e-check.txt && git status --short e2e-check.txt"
        exec_payload = {
            "project_id": project_id,
            "password": project_password,
            "cmd": exec_command,
        }
        exec_response = client.post("/exec", json=exec_payload)
        assert exec_response.status_code == 200, exec_response.text
        exec_data = exec_response.json()
        assert exec_data["returncode"] == 0
        assert "e2e-check.txt" in exec_data["stdout"]

        # ------------------------------------------------------------------
        # Step 3: Query project info to validate container status persisted.
        # ------------------------------------------------------------------
        info_payload = {"project_id": project_id, "password": project_password}
        info_response = client.post("/projects/info", json=info_payload)
        assert info_response.status_code == 200, info_response.text
        info_data = info_response.json()
        assert info_data["status"] in {"running", "created", "active"}
        assert info_data["container_id"], "container_id should be cached in Redis/SQLite"

        # ------------------------------------------------------------------
        # Step 4: Commit the generated file via the git endpoint.
        # ------------------------------------------------------------------
        commit_payload = {
            "project_id": project_id,
            "password": project_password,
            "message": f"E2E verification {project_suffix}",
            "add_all": True,
        }
        commit_response = client.post("/git/commit", json=commit_payload)
        assert commit_response.status_code == 200, commit_response.text
        commit_data = commit_response.json()
        assert commit_data["returncode"] == 0
        assert commit_data["backup_path"], "Backup path should be returned after commit"

        # Verify the metadata reflects the latest state after the commit.
        post_commit_info = client.post("/projects/info", json=info_payload)
        assert post_commit_info.status_code == 200, post_commit_info.text
        refreshed = post_commit_info.json()
        assert refreshed["container_id"] == info_data["container_id"]

        # Final check to ensure the project remains listed for the user.
        refreshed_list = client.get(f"/projects/{username}", headers=list_headers)
        assert refreshed_list.status_code == 200, refreshed_list.text
        assert any(item["project_id"] == project_id for item in refreshed_list.json().get("projects", []))

        # Optional cleanup to avoid leaking test projects in shared environments.
        client.request(
            "DELETE",
            "/projects/delete",
            json={"project_id": project_id, "password": project_password},
        )
